Cart/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.cart,name="cart"),
    path('add_cart/<int:product_id>/',views.add_cart,name="add_cart"),
    path('decrement_cart/<int:product_id>/<int:cart_item_id>/',views.decrement_cart,name="decrement_cart"),
    path('remove_from_cart/<int:product_id>/<int:cart_item_id>/',views.remove_from_cart,name="remove_from_cart"),
    path('checkout/',views.checkout,name='checkout')

]

EcommerceStore/urls.py
from django.contrib import admin
from django.urls import path,include

from EcommerceStore.settings import MEDIA_URL
from EcommerceStore import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('store/',include('Store.urls')),
    path('cart/',include('Cart.urls')),
    path('accounts/',include('Accounts.urls')),
    path('orders/',include('Orders.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Store/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.store,name="store"),
    path('category/<slug:category_slug>/',views.store,name="store_products_category"),
    path('category/<slug:category_slug>/<slug:product_slug>/',views.product_detail,name="product_detail"),
    path('search/',views.search,name='search'),
    path('reviews/<int:product_id>/',views.reviews,name='reviews')
]

Cart/models.py
from django.db import models
from Store.models import ProductVariation
from Store.models import Product
from Accounts.models import Account
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250)
    added_date=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    user=models.ForeignKey(Account,on_delete=models.CASCADE,null=True)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    product_variation=models.ManyToManyField(ProductVariation,blank=True)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE,null=True)
    is_active=models.BooleanField(default=True)
    quantity=models.IntegerField()

    def __unicode__(self):
        return self.product
    def sub_total(self):
        return self.quantity*self.product.price

Store/models.py
from django.db import models
from django.db.models import Avg,Count
from Category.models import Category
from django.urls import reverse
from Accounts.models import Account
# Create your models here.
class Product(models.Model):
    product_name    =models.CharField(max_length=200,unique=True)
    slug            =models.SlugField(max_length=200,unique=True)
    description     =models.TextField(max_length=500,blank=True)
    price           =models.IntegerField()
    image           =models.ImageField(upload_to='photos/products') 
    stock           =models.IntegerField()
    is_available    =models.BooleanField(default=True)
    category        =models.ForeignKey(Category,on_delete=models.CASCADE)
    created_date    =models.DateTimeField(auto_now_add=True)
    modified_date   =models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name

    def get_url(self):
        return reverse('product_detail',args=[self.category.slug,self.slug])
    
    def average_rating(self):
        average=ReviewRating.objects.filter(product=self,status=True).aggregate(average=Avg('rating'))
        if average['average'] is not None:
            return float(average['average'])
        return 'There is no sufficient reviews to rate this product'
    def review_count(self):
        review_count=ReviewRating.objects.filter(product=self,status=True).aggregate(count=Count('id'))
        counter=0
        if review_count['count'] is not None:
            return review_count['count']
        return counter

# customising returned queryset
class VariationsManager(models.Manager):
    def colors(self):
        return super(VariationsManager,self).filter(variation_category='color',is_active=True)

    def sizes(self):
        return super(VariationsManager,self).filter(variation_category='size',is_active=True)

variation_category_choices=(
    ('color','color'),
    ('size','size'),
    )
class ProductVariation(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    variation_category=models.CharField(max_length=100,choices=variation_category_choices)
    variation_value=models.CharField(max_length=100)
    is_active=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now=True)
    objects=VariationsManager()
    def __str__(self):
        return self.variation_value

class ReviewRating(models.Model):
    user=models.ForeignKey(Account,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    status=models.BooleanField(default=True)
    ip=models.CharField(max_length=20,blank=True)
    subject=models.CharField(max_length=100,blank=True)
    review=models.TextField(max_length=500,blank=True)
    rating=models.FloatField()
    created_at=models.DateField(auto_now_add=True)
    updated_at=models.DateField(auto_now=True)

    def __str__(self):
        return self.subject

Store/forms.py
from django import forms
from .models import ReviewRating

class RatingsForm(forms.ModelForm):
    class Meta:
        model=ReviewRating
        fields=['subject','review','rating']

Cart/views.py
from django.shortcuts import HttpResponse, get_object_or_404, render,redirect

from Cart.models import CartItem,Cart
from Store.models import ProductVariation
from Store.models import Product
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required



# Create your views here.
def cart(request,cartItems=None,totalPrice=0,tax=0,grandTotal=0):
    try:
        if request.user.is_authenticated:
            cartItems=CartItem.objects.all().filter(user=request.user,is_active=True)
        else:
            cartObject=Cart.objects.get(cart_id=request.session.session_key)
            cartItems=CartItem.objects.all().filter(cart=cartObject,is_active=True)
        for item in cartItems:
            totalPrice+=item.product.price*item.quantity
        tax=.02*totalPrice
        grandTotal=totalPrice+tax
    except ObjectDoesNotExist:
        pass
    context={
        'cartItems':cartItems,
        'totalPrice':totalPrice,
        'tax':tax,
        'grandTotal':grandTotal
    }
    return render(request,'store/cart.html',context)
def _get_session_id(request):
    session_id=request.session.session_key
    if not session_id:
        session_id=request.session.create()
    return session_id

def add_cart(request,product_id):
    if request.method=='POST':
        if request.POST:
            for item in request.POST:
                key=item
                value=request.POST[key]
                
    product=Product.objects.get(id=product_id) #i think the id is the autoincrementing autoassigned unique pk
    variationList=[]
    if request.method=='POST':
        for item in request.POST:
            key=item
            value=request.POST[key]
            try:
                variation=ProductVariation.objects.get(product=product,variation_category__iexact=key,variation_value__iexact=value)
                variationList.append(variation)
            except Exception:
                pass
    try:
        cart=Cart.objects.get(cart_id=_get_session_id(request)) #
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_get_session_id(request))
        cart.save()
    current_user=request.user
    if current_user.is_authenticated:
        cart_item_exists=CartItem.objects.filter(product=product,user=current_user).exists()
        if cart_item_exists:
            cart_items=CartItem.objects.filter(product=product,user=current_user)
            existing_variations=[]
            for cart_item in cart_items:
                instance_variations=cart_item.product_variation.all()
                existing_variations.append(list(instance_variations))
            if variationList in existing_variations:
                cart_item_idx=existing_variations.index(variationList)
                cart_item=cart_items[cart_item_idx]
                cart_item.quantity+=1
            else:
                cart_item=CartItem.objects.create(product=product,user=current_user,quantity=1)
                cart_item.product_variation.clear()
                cart_item.product_variation.add(*variationList)
        else:
            cart_item=CartItem.objects.create(product=product,user=current_user,quantity=1)
            cart_item.product_variation.clear()
            if len(variationList):
                cart_item.product_variation.add(*variationList)
    else:
        cart_item_exists=CartItem.objects.filter(product=product,cart=cart).exists()
        if cart_item_exists:
            cart_items=CartItem.objects.filter(product=product,cart=cart)
            existing_variations=[]
            for cart_item in cart_items:
                instance_variations=cart_item.product_variation.all()
                existing_variations.append(list(instance_variations))
            if variationList in existing_variations:
                cart_item_idx=existing_variations.index(variationList)
                cart_item=cart_items[cart_item_idx]
                cart_item.quantity+=1
            else:
                cart_item=CartItem.objects.create(product=product,cart=cart,quantity=1)
                cart_item.product_variation.clear()
                cart_item.product_variation.add(*variationList)
        else:
            cart_item=CartItem.objects.create(product=product,cart=cart,quantity=1)
            cart_item.product_variation.clear()
            if len(variationList):
                cart_item.product_variation.add(*variationList)
    cart_item.save()
    return redirect('cart')

def decrement_cart(request,product_id,cart_item_id):
    item=get_object_or_404(Product,id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item=CartItem.objects.get(product=item,user=request.user,id=cart_item_id)
        else:
            cart=Cart.objects.get(cart_id=_get_session_id(request)) 
            cart_item=CartItem.objects.get(product=item,cart=cart,id=cart_item_id)
        if cart_item.quantity<=1:
            return redirect('remove_from_cart',product_id,cart_item_id)
        cart_item.quantity-=1
        cart_item.save()
    except:
        pass
    return redirect('cart')
    

def remove_from_cart(request,product_id,cart_item_id):
    item=get_object_or_404(Product,id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item=CartItem.objects.get(product=item,user=request.user,id=cart_item_id)
        else:  
            cart=Cart.objects.get(cart_id=_get_session_id(request))
            cart_item=CartItem.objects.get(product=item,cart=cart,id=cart_item_id)
        cart_item.delete()
    except:
        pass
    return redirect('cart')
@login_required(login_url='login')
def checkout(request,cartItems=None,totalPrice=0,tax=0,grandTotal=0):
    try:
        if request.user.is_authenticated:
            cartItems=CartItem.objects.all().filter(user=request.user,is_active=True)
        else:
            cartObject=Cart.objects.get(cart_id=request.session.session_key)
            cartItems=CartItem.objects.all().filter(cart=cartObject,is_active=True)
        for item in cartItems:
            totalPrice+=item.product.price*item.quantity
        tax=.02*totalPrice
        grandTotal=totalPrice+tax
    except ObjectDoesNotExist:
        pass
    context={
        'cartItems':cartItems,
        'totalPrice':totalPrice,
        'tax':tax,
        'grandTotal':grandTotal
    }
    return render(request,'store/checkout.html',context)
  

Store/views.py
from nis import cat
from threading import get_ident
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib import messages
from .models import Product,ReviewRating
from .forms import RatingsForm
from Orders.models import OrderProduct
from Category.models import Category
from Cart.models import CartItem
from Cart.views import _get_session_id
from django.core.paginator import PageNotAnInteger,EmptyPage,Paginator
from django.db.models import Q


# Create your views here.
def store(request,category_slug=None):
    if category_slug:
        categories=get_object_or_404(Category,slug=category_slug)
        products=Product.objects.all().filter(category=categories,is_available=True).order_by('id')
        paginator=Paginator(products,1)
        page_num=request.GET.get('page')
        paged_products=paginator.get_page(page_num)
    else:
        products=Product.objects.all().filter(is_available=True).order_by('id')
        paginator=Paginator(products,6)
        page_num=request.GET.get('page')
        paged_products=paginator.get_page(page_num)
    context={
        'page_num':page_num,
        'page':paged_products,
        'products_count':products.count()
    }
    return render(request,'store/store.html',context)

def product_detail(request,category_slug=None,product_slug=None):
    try:
        product=Product.objects.get(category__slug=category_slug,slug=product_slug)
        in_cart=CartItem.objects.filter(cart__cart_id=_get_session_id(request),product=product).exists()
    except Exception as e:
        return e
    try:
        bought_product=OrderProduct.objects.filter(user_id=request.user.id,product_id=product.id).exists()
    except OrderProduct.DoesNotExist:
        bought_product=None
    try:
        product_reviews=ReviewRating.objects.filter(product_id=product.id,status=True)
    except ReviewRating.DoesNotExist:
        product_reviews=None
    context={
        'product':product,
        'in_cart':in_cart,
        'has_bought_product':bought_product,
        'product_reviews':product_reviews
    }
    return render(request,'store/product_detail.html',context)

def search(request):
    if 'keyword' in request.GET:
        keyword=request.GET['keyword']
        if keyword:
            products=Product.objects.order_by('created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            paginator=Paginator(products,8)
            page_num=request.GET.get('page')
            paged_products=paginator.get_page(page_num)
        else:
            return redirect('store')
    context={
        'page_num':page_num,
        'page':paged_products,
        'products_count':products.count(),
        'search_keyword':keyword
        }
    return render(request,'store/store.html',context)

def reviews(request,product_id):
    url=request.META.get('HTTP_REFERER')
    if request.method=='POST':
        try:
            reviews_=ReviewRating.objects.get(user_id=request.user.id,product_id=product_id)
            form=RatingsForm(request.POST,instance=reviews_)
            form.save()
            messages.success(request,'Thank you. Your review has been updated successfully!')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form=RatingsForm(request.POST)
            if form.is_valid():
                rating=ReviewRating()
                rating.user_id=request.user.id
                rating.product_id=product_id
                rating.subject=form.cleaned_data['subject']
                rating.review=form.cleaned_data['review']
                rating.rating=form.cleaned_data['rating']
                rating.ip=request.META.get('REMOTE_ADDR')
                rating.save()
                messages.success(request,'Thank you! Your review has been received. If you have any concerns please contact our support center')
                return redirect(url)
        return redirect(url)

templates/store/cart.html
{%extends 'base.html'%}
{% load static %}

{% block content%}
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    {% if not cartItems%}
        <h2 class="text-center">Your Cart is empty</h2>  
        <div class="text-center">
            <a href="{%url 'store'%}" class="btn btn-primary"> Continue shopping</a>
        </div>
    {% else%} 
    <div class="row">
        <aside class="col-lg-9">
    <div class="card">
    <table class="table table-borderless table-shopping-cart">
    <thead class="text-muted">
    <tr class="small text-uppercase">
      <th scope="col">Product</th>
      <th scope="col" width="120">Quantity</th>
      <th scope="col" width="120">Price</th>
      <th scope="col" class="text-right" width="200"> </th>
    </tr>
    </thead>
    <tbody>

        {% for cart_item in cartItems%}
        <tr>
            <td>
                <figure class="itemside align-items-center">
                    <div class="aside"><img src="{{cart_item.product.image.url}}" class="img-sm"></div>
                    <figcaption class="info">
                        <a href="{{cart_item.product.get_url}}" class="title text-dark">{{cart_item.product.product_name}}</a>
                        <p class="text-muted small">
                            {% if cart_item.product_variation.all %}
                                {% for item in cart_item.product_variation.all %}
                                    {{item.variation_category | lower}}: {{item.variation_value | capfirst}}
                                    <br> 
                                {% endfor %}
                            {% endif %}
                        </p>
                    </figcaption>
                </figure>
            </td>
            <td> 
                <!-- col.// -->
                            <div class="col"> 
                                <div class="input-group input-spinner">
                                    <div class="input-group-prepend">
                                    <a href="{%url 'decrement_cart' cart_item.product.id cart_item.id%}"><button class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </button></a>
                                    </div>
                                    <input type="text" class="form-control"  value="{{cart_item.quantity}}">
                                    <div class="input-group-append">
                                    <form action="{%url 'add_cart' cart_item.product.id%}" method="POST"> {% csrf_token %}
                                        {% for item in cart_item.product_variation.all %}
                                            <input type="hidden" name="{{item.variation_category | lower}}" value="{{item.variation_value | capfirst}}">
                                        {% endfor %}
                                        <button class="btn btn-light" type="submit" id="button-minus" > <i class="fa fa-plus"></i></button>
                                    </form>
                                    </div>
                                </div> <!-- input-group.// -->
                            </div> <!-- col.// -->
            </td>
            <td> 
                <div class="price-wrap"> 
                    <var class="price">${{cart_item.sub_total}}.00</var> 
                    <small class="text-muted"> ${{cart_item.product.price}} each </small> 
                </div> <!-- price-wrap .// -->
            </td>
            <td class="text-right"> 
            <a href="{%url 'remove_from_cart' cart_item.product.id cart_item.id%}" onclick="return confirm('This {{cart_item.product.product_name}} will be deleted from your Cart!') "class="btn btn-danger"> Remove</a>
            </td>
        </tr>
        {%endfor%}
    </tbody>
    </table>
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">${{totalPrice}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> ${{tax}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>${{grandTotal}}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{%static './images/misc/payments.png'%}" height="26">
                </p>
                <a href="{%url 'checkout'%}" class="btn btn-primary btn-block"> Checkout </a>
                <a href="{%url 'store'%}" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    {%endif%}
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    </body>
    </html>
    {% endblock content%}

templates/store/product_detail.html
{%extends 'base.html'%}
{%load static%}

{%block content%}
<section class="section-content padding-y bg">

    {%include 'includes/alerts.html'%}
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <div class="img-big-wrap">
           <a href="#"><img src="{{product.image.url}}"></a>
        </div> <!-- img-big-wrap.// -->
        
    </article> <!-- gallery-wrap .end// -->
            </aside>
            <main class="col-md-6 border-left">
   <form action="{% url 'add_cart' product.id %}" method="post" > {% csrf_token %}
    <article class="content-body">
        <h2 class="title">{{product.product_name}}</h2> 
        <div class="rating-star">
            <span>
                <i class="fa fa-star{%if product.average_rating == 0.5%}-half-o{%elif product.average_rating < 1%}-o {%endif%}" aria-hidden="true"></i>
                <i class="fa fa-star{%if product.average_rating == 1.5%}-half-o{%elif product.average_rating < 2%}-o {%endif%}" aria-hidden="true"></i>
                <i class="fa fa-star{%if product.average_rating == 2.5%}-half-o{%elif product.average_rating < 3%}-o {%endif%}" aria-hidden="true"></i>
                <i class="fa fa-star{%if product.average_rating == 3.5%}-half-o{%elif product.average_rating < 4%}-o {%endif%}" aria-hidden="true"></i>
                <i class="fa fa-star{%if product.average_rating == 4.5%}-half-o{%elif product.average_rating < 5%}-o {%endif%}" aria-hidden="true"></i>
           <span class="text-muted"> {{product.review_count}} review{{product.review_count|pluralize:'s'}}</span>
            </span>
        </div>  
         <div class="mb-3">
            <var class="price h4">${{product.price}}.00</var> 
        </div> 
        <p>{{product.description}}.</p>
        <hr>
          <div class="row">
              <div class="item-option-select">
                  <h6>Choose Color</h6>
                    <select name="color" class="form-control" required>
                        <option value="" disabled selected>select</option>
                            {% for i in product.productvariation_set.colors%}
                        <option {{i.variation_value|lower}}>{{i.variation_value | capfirst }}</option>
                            {% endfor %}
                    </select>
              </div>
          </div> <!-- row.// -->
          <div class="row">
              <div class="item-option-select">
                  <h6>Select Size</h6>
                    <select name="size" class="form-control">
                        <option value="" disabled selected>select</option>
                            {% for i in product.productvariation_set.sizes%}
                        <option {{i.variation_value|lower}}>{{i.variation_value | capfirst }}</option>
                            {% endfor %}
                    </select>
              </div>
          </div> <!-- row.// -->
          <hr>

          {% if product.stock <= 0%}
              <h5 class="text-danger">Oops!This {{product.product_name}} is out of stock</h5>
          {% else %}
              <button type="submit" class="btn  btn-primary"> <span class="text">Add to Cart</span> <i class="fas fa-shopping-cart"></i>  </button>
          {% endif %}
      </article> <!-- product-info-aside .// -->
   </form>
            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    
    <div class="row">
                <div class="col-md-9">
    <form action="{%url 'reviews' product.id%}" method="POST">
        {% csrf_token %}
        <h5>Write your review</h5>
        <!-- ratings section -->
        <div>
            <label>How do you rate this {{product.category}}</label>
            <br>

            <div class="rate">
                <input type="radio" name="rating" value="5" id="rating10" required/><label for="rating10" title="5"></label>
                <input type="radio" name="rating" value="4.5" id="rating9" required/><label for="rating9" title="4.5" class="half"></label>
                <input type="radio" name="rating" value="4" id="rating8" required/><label for="rating8" title="4"></label>
                <input type="radio" name="rating" value="3.5" id="rating7" required/><label for="rating7" title="3.5" class="half"></label>
                <input type="radio" name="rating" value="3" id="rating6" required/><label for="rating6" title="3"></label>
                <input type="radio" name="rating" value="2.5" id="rating5" required/><label for="rating5" title="2.5" class="half"></label>
                <input type="radio" name="rating" value="2" id="rating4" required/><label for="rating4" title="2"></label>
                <input type="radio" name="rating" value="1.5" id="rating3" required/><label for="rating3" title="1.5" class="half"></label>
                <input type="radio" name="rating" value="1" id="rating2" required/><label for="rating2" title="1"></label>
                <input type="radio" name="rating" value="0.5" id="rating1" required/><label for="rating1" title="0.5" class="half"></label>
            </div>
            <br>
            Subject:
            <input type="text" name="subject" class="form-control">
            <br>
            Review:
            <textarea name="review" rows="4" class="form-control"></textarea>
            <br>
            
            {%if request.user.is_authenticated%}
                {%if has_bought_product%}
                    <input type="submit" class="btn btn-primary" value="Submit Review">
                {%else%}
                    <p>Sorry! Only those who have purchased this product can review it.</p>
                {%endif%}
            {%else%}
                <p>Login to review this product. <a href="{%url 'login'%}">Login</a> </p>
            {%endif%}
        </div>
    </form>
    <header class="section-heading">
        <h3>Customer Reviews </h3>  
    </header>
    <div class="rating-star">
        Average rating: 
        <span>
            <i class="fa fa-star{%if product.average_rating == 0.5%}-half-o{%elif product.average_rating < 1%}-o {%endif%}" aria-hidden="true"></i>
            <i class="fa fa-star{%if product.average_rating == 1.5%}-half-o{%elif product.average_rating < 2%}-o {%endif%}" aria-hidden="true"></i>
            <i class="fa fa-star{%if product.average_rating == 2.5%}-half-o{%elif product.average_rating < 3%}-o {%endif%}" aria-hidden="true"></i>
            <i class="fa fa-star{%if product.average_rating == 3.5%}-half-o{%elif product.average_rating < 4%}-o {%endif%}" aria-hidden="true"></i>
            <i class="fa fa-star{%if product.average_rating == 4.5%}-half-o{%elif product.average_rating < 5%}-o {%endif%}" aria-hidden="true"></i>
       
            <span class="text-muted"> {{product.review_count}} review{{product.review_count|pluralize:'s'}}</span>
        </span>
    </div>  
    {% for review in product_reviews %}
        <article class="box mb-3">
            <div class="icontext w-100">
                <img src="{%static './images/portrait.jpg'%}" class="img-xs icon rounded-circle">
                <div class="text">
                    <span class="date text-muted float-md-right">{{review.updated_at}} </span>  
                    <br>
                    <h6 class="mb-1">{{review.user.first_name|capfirst}} </h6>

                    <div class="rating-star">
                        <span>
                            <i class="fa fa-star{%if review.rating == 0.5%}-half-o{%elif review.rating < 1%}-o {%endif%}" aria-hidden="true"></i>
                            <i class="fa fa-star{%if review.rating == 1.5%}-half-o{%elif review.rating < 2%}-o {%endif%}" aria-hidden="true"></i>
                            <i class="fa fa-star{%if review.rating == 2.5%}-half-o{%elif review.rating < 3%}-o {%endif%}" aria-hidden="true"></i>
                            <i class="fa fa-star{%if review.rating == 3.5%}-half-o{%elif review.rating < 4%}-o {%endif%}" aria-hidden="true"></i>
                            <i class="fa fa-star{%if review.rating == 4.5%}-half-o{%elif review.rating < 5%}-o {%endif%}" aria-hidden="true"></i>
                        </span>
                    </div>  
                </div>
                
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <h6>{{review.subject}}</h6>
                <p>
                    {{review.review}}
                </p>	
            </div>
        </article>
        {% endfor %}
    
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    
    </body>
    </html>
{%endblock%}